### ISSUE TITLE
[Feature Request] Image preview using telescope-media-files.nvim

### ISSUE THREAD

**Issue by AndOrangutan** [nvim-neorg/neorg-telescope#14]
I came across [renerocksai/telekasten.nvim](https://github.com/renerocksai/telekasten.nvim) and really like how they use [nvim-telescope/telescope-media-files.nvim](https://github.com/nvim-telescope/telescope-media-files.nvim) to preview images. Something like this would make Neorg much more competitive with something like Markdown.
![2022-01-26_01-27](https://user-images.githubusercontent.com/40435989/151137438-34c72783-2d57-4906-88cf-d5f23ce65222.png)

**Comment by max397574** [comment]
which images would you preview?

**Comment by max397574** [comment]
closing because it's not clear at all what's wanted here
reopen if you like
