### ISSUE TITLE
[Feature Request] Search neorg filenames in workspace (find_file)

### ISSUE THREAD

**Issue by kandodev** [nvim-neorg/neorg-telescope#27]
Should be simple enough but we have find_linkable. Need the same thing but it should be on the filenames limited to the current workspace. Selecting it should open that neorg file.

**Comment by max397574** [comment]
just use `Telescope find_files` with patterns

**Comment by codevion** [comment]
I would need to find workspace root and then cut off the filepath prefixes behind the workspace root so it's clean. I really just want the same picker as `Telescope neorg insert_file_link` but to navigate to the selection instead of inserting it as a link.

**Comment by max397574** [comment]
`require"telescope.builtin".find_files({cwd=neorg.modules.get_module("core.dirman").get_workspace(neorg.modules.get_module("core.dirman").get_current_workspace())` should work

**Comment by codevion** [comment]
That doesn't work. Is there perhaps another function after that to actually get the path for the current workspace?

**Comment by codevion** [comment]
Ah nvm, just needed to adjust it to core.norg.dirman instead. That works, thanks!o
