### ISSUE TITLE
<C-l> in insert mode is always active

### ISSUE THREAD

**Issue by svenXY** [nvim-neorg/neorg-telescope#32]
Hi,
I'm using `<c-l>` in insert mode for other things (luasnips), therefore I'd like to remap them to something else here.

I have set

```lua
    local neorg_callbacks = require("neorg.callbacks")

    neorg_callbacks.on_event("core.keybinds.events.enable_keybinds", function(_, keybinds)
      -- Map all the below keybinds only when the "norg" mode is active
      keybinds.map_event_to_mode("norg", {
        i = { -- Bind  in insert mode
          { "<C-L>", "core.integrations.telescope.insert_link" }, -- capital L here
        },
      }, {
          silent = true,
          noremap = true,
        })
    end)
```

but `<c-l>` in insert mode is still active. Can the mapping be removed somehow?

**Comment by svenXY** [comment]
never mind - (n)vim cannot distinguish between `<c-L>` and `<c-l>`, so I had to switch wo `<c-i>` (read: *I*nsert) instead.

**Comment by BoManev** [comment]
I think this is a limitation of the terminal and not vim
In alacritty I use the following:
`- { key: L, mods: Control|Shift, chars: "\x1b[76;5u" }`
