### ISSUE TITLE
Error `module 'neorg.modules.base' not found` 

### ISSUE THREAD

**Issue by Tony-Sol** [nvim-neorg/neorg-telescope#39]
I installed extension via lazy.nvim (like this how https://github.com/Tony-Sol/.config/blob/master/nvim/lua/plugins/neorg.lua, very similar to readme) and started to get this error:

<img width="1229" alt="Снимок экрана 2023-08-01 в 15 36 16" src="https://github.com/nvim-neorg/neorg-telescope/assets/33671815/10a379de-5af2-4a9b-81b0-774255a40228">

Looks like, it caused by this https://github.com/nvim-neorg/neorg/commit/5706f1efdcf55f273de8f52deeb35375a303be72 change in Neorg

**Comment by max397574** [comment]
duplicate https://github.com/nvim-neorg/neorg-telescope/issues/38
