### ISSUE TITLE
Request: Use semver to indicate compatibility with `neorg` main plugin

### ISSUE THREAD

**Issue by leon-richardt** [nvim-neorg/neorg-telescope#40]
Hey all,

First, let me say thank you for the great job you are doing with this project.

As I'm sure you're aware, many plugin managers (e.g. lazy.nvim) can be configured to only update plugins once a new version is released. In this particular case, I think it could be beneficial for the project to make sure that both the most recent release of the main repo ([`neorg`](https://github.com/nvim-neorg/neorg)) and this one are compatible with one another.

For example, currently, my local plugin version of `nvim-neorg` is at [`v5.0.0`](https://github.com/nvim-neorg/neorg/tree/v5.0.0) whereas `neorg-telescope` is at d803ae4. Without further user interaction, this breaks `neorg-telescope` (due to [`neorg@5706f1e`](https://github.com/nvim-neorg/neorg/commit/5706f1efdcf55f273de8f52deeb35375a303be72), I assume). In the future, this could be prevented by releasing new versions "simultaneously" (or close to it).

Thank you for your time & consideration :smile:

**Comment by vhyrro** [comment]
Hey, I totally agree! In fact the reason this doesn't have semver is because I forgot to add it, lol. Will do that soon.

**Comment by vhyrro** [comment]
Released `1.0.0`! Any breaking changes will now be a new semver bump :D
