### ISSUE TITLE
Possible error in link creation.

### ISSUE THREAD

**Issue by AndOrangutan** [nvim-neorg/neorg-telescope#5]
When I go to create a link to a file it creates a relative file path.
![2021-11-12_01-55](https://user-images.githubusercontent.com/40435989/141448451-f6abe383-2e7a-4de3-8138-8590e6b3eee5.png)
 
![2021-11-12_01-55_1](https://user-images.githubusercontent.com/40435989/141448469-eec60709-8e66-4752-b756-1a21d6b9b03c.png)

Shouldn't the Link look like this?
![2021-11-12_01-55_2](https://user-images.githubusercontent.com/40435989/141448482-96181ef8-962e-4ba0-9711-81f804ad565f.png)

**Comment by trekdemo** [comment]
@AndOrangutan To confirm the difference: Are you missing a `/` prefix?

AFAICS the link created by the telescope integration is relative to the [current workspace](https://github.com/nvim-neorg/neorg-telescope/blob/main/lua/telescope/_extensions/neorg/insert_link.lua#L12-L14) (managed by dirman).
For me, the links inserted by this extension work fine.

Did you run into some issues when you try to follow the links?

**Comment by danymat** [comment]
Hello, can you try again with the new link format ?

**Comment by max397574** [comment]
is this fixed now @AndOrangutan ?

**Comment by max397574** [comment]
closing this
reopen if it isn't fixed
