### ISSUE TITLE
Unable to link after using Neorg journal

### ISSUE THREAD

**Issue by Halleyscomet0855** [nvim-neorg/neorg-telescope#53]
Setup to reproduce bug(?):
1. Open neovim.
2. Run the journal command `:Neorg journal today`
3. Run the find file link command, `:Telescope neorg insert_file_link`
4. Expected behavior: telescope searches all files for a valid link
5. Actual behavior: Telescope ui appears, but contains no files to add.

Thinking paragraph:
My intuition with this is that:
1. By entering the journal, I did not set my workspace property as "notes". 
2. The integration asks Telescope to search my workspace to obtain files.
3. Since I didn't have a workspace property, Telescope doesn't seem to know where to search the files.

The issue is that when I load my NvChad setup, it works, albeit being very, very slow. So that's something that may go against my logic above.

~~Attached are comparisons between personal config and NvChad config~~ OBS has crashed on me. Will add as soon as I can.

UPDATE: 

For some reason, and I literally have no idea why, but my personal config actually does the same thing as the NvChad config? I edited nothing, and did the same steps, but now all it does is load a while before continuing normally. 
I've tested entering the journal while in a file, but it had the same behaviour.

**Comment by pysan3** [comment]
Upload your config or we can't help you. 

Upload both neorg and telescope config. 

I assume NvChad's config for telescope correctly finds `fd` or `ripgrep` whereas your config has no setup for that.

**Comment by max397574** [comment]
@Halleyscomet0855 please provide your configuration

**Comment by Halleyscomet0855** [comment]
Hi, unfortunately, I've dropped Neorg (and by extension neorg-telescope) from my nvim system, because I've had too much difficulty incorporating it into my existing workflow. Sorry for the inconvenience.
