### ISSUE TITLE
Some calls are erroring out

### ISSUE THREAD

**Issue by davidbgonz** [nvim-neorg/neorg-telescope#57]
First noticed that the `find_neorg_files` call was throwing error. Going though all the calls, I am getting the below errors for some methods when I call them in the cmdline. Hopefully these are helpful to see a pattern. I know recently there's been a lot of changes with telescope and neorg. 

~~find_aof_tasks:~~ _known issue: this can be ignored_
![image](https://github.com/nvim-neorg/neorg-telescope/assets/10837237/40f6fc30-e26c-4674-b525-a99953bc2214)

find_norg_files:
![image](https://github.com/nvim-neorg/neorg-telescope/assets/10837237/6653c1ec-6608-440e-bf94-07d366ad0547)

switch_workspace:
Telescope popup appears, but then after a few seconds this error shows
![image](https://github.com/nvim-neorg/neorg-telescope/assets/10837237/dd597c8c-798c-47db-9a5a-bb3ec15faebf)

~~find_context_tasks:~~ _known issue: this can be ignored_
![image](https://github.com/nvim-neorg/neorg-telescope/assets/10837237/c121ffdf-a93b-4f2b-b17b-8e3b09676b95)

~~find_project_tasks:~~ _known issue: this can be ignored_
![image](https://github.com/nvim-neorg/neorg-telescope/assets/10837237/ae93c756-1853-4915-95d4-43e93b1d808d)

~~find_aof_project_tasks:~~ _known issue: this can be ignored_
![image](https://github.com/nvim-neorg/neorg-telescope/assets/10837237/0ce7a41e-4949-435e-9c98-0c8e0f16c45c)

Rest of the calls are working for me. Let me know if there is additional information you need from my setup. Everything is setup/up-to-date through lazy. I'm on v8.x of neorg with the luarocks integration with lazy.

**Comment by austinbutler** [comment]
Possibly related: https://github.com/nvim-neorg/neorg-telescope/pull/58

**Comment by benlubas** [comment]
@davidbgonz all of the task pickers are known to be broken, they're listed as such in the readme. 

The other two were fixed shortly after this issue went up, if you still have problems you can leave them here or open a new issue but otherwise this one can be closed

**Comment by davidbgonz** [comment]
Thanks for letting me know on the task picker calls. I'll update the original message to mark that.

I still have the above errors running the `find_norg_files` and `switch_workspace` calls.

**Comment by benlubas** [comment]
ah, try out #58, should fix that

**Comment by davidbgonz** [comment]
Yep, the changes in that PR works for me. All the calls are functional again. I appreciate you taking the time helping me out. This is one of those extensions that you don't realize how much you lean on it until it starts throwing errors. I'll close this issue out and in the meantime I will patiently wait for that PR to be merged.

**Comment by benlubas** [comment]
You can (and probably should) leave it open until the pr is merged.

**Comment by pysan3** [comment]
- https://github.com/nvim-neorg/neorg-telescope/pull/58

It is now merged. 
I think we can close this (I don't have the permission).

**Comment by davidbgonz** [comment]
Thanks for the PR! Closing this now.
