### ISSUE TITLE
 module neorg.modules.core.integrations.telescope.module not found

### ISSUE THREAD

**Issue by ivanenev** [nvim-neorg/neorg-telescope#61]
Hi, I am new to neorg and have no idea how to fix the errors I am getting. I hope someone with experience can help. 

 Here is the error I am getting: 

[neorg] (16:22:56)
.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:447
Unable to load module 'core.integrations.telescope'. The module probably does not exist! Stacktrace:  module 'neorg.modules.core.integrations.telescope.module' not found:No LuaRocks module found for neorg.modules.core.integrations.telescope.module
	no field package.preload['neorg.modules.core.integrations.telescope.module']
cache_loader: module neorg.modules.core.integrations.telescope.module not found
cache_loader_lib: module neorg.modules.core.integrations.telescope.module not found
	no file './neorg/modules/core/integrations/telescope/module.lua'
	no file '/usr/share/luajit-2.1/neorg/modules/core/integrations/telescope/module.lua'
	no file '/usr/local/share/lua/5.1/neorg/modules/core/integrations/telescope/module.lua'
	no file '/usr/local/share/lua/5.1/neorg/modules/core/integrations/telescope/module/init.lua'
	no file '/usr/share/lua/5.1/neorg/modules/core/integrations/telescope/module.lua'
	no file '/usr/share/lua/5.1/neorg/modules/core/integrations/telescope/module/init.lua'
	no file '/home/mts/.local/share/nvim/lazy/luarocks.nvim/.rocks/share/lua/5.1/neorg/modules/core/integrations/telescope/module.lua'
	no file '/home/mts/.local/share/nvim/lazy/luarocks.nvim/.rocks/share/lua/5.1/neorg/modules/core/integrations/telescope/module/init.lua'
	no file '/home/mts/.local/share/nvim/lazy/luarocks.nvim/.rocks/lua/neorg/modules/core/integrations/telescope/module.lua'
	no file '/home/mts/.local/share/nvim/lazy/luarocks.nvim/.rocks/lua/neorg/modules/core/integrations/telescope/module/init.lua'
	no file '/home/mts/.luarocks/share/lua/5.1/neorg/modules/core/integrations/telescope/module.lua'
	no file '/home/mts/.luarocks/share/lua/5.1/neorg/modules/core/integrations/telescope/module/init.lua'
	no file './neorg/modules/core/integrations/telescope/module.so'
	no file '/usr/local/lib/lua/5.1/neorg/modules/core/integrations/telescope/module.so'
	no file '/usr/lib/lua/5.1/neorg/modules/core/integrations/telescope/module.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/mts/.local/share/nvim/lazy/luarocks.nvim/.rocks/lib/lua/5.1/neorg/modules/core/integrations/telescope/module.so'
	no file '/home/mts/.luarocks/lib/lua/5.1/neorg/modules/core/integrations/telescope/module.so'
	no file './neorg.so'
	no file '/usr/local/lib/lua/5.1/neorg.so'
	no file '/usr/lib/lua/5.1/neorg.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/mts/.local/share/nvim/lazy/luarocks.nvim/.rocks/lib/lua/5.1/neorg.so'
	no file '/home/mts/.luarocks/lib/lua/5.1/neorg.so'

here is the Nvim plugin i am using:

return {
  "nvim-neorg/neorg",
  version = "^8",
  dependencies = {
    {
      "vhyrro/luarocks.nvim",
      priority = 1000, -- We'd like this plugin to load first out of the rest
      config = true,
    },
  },
  event = "VeryLazy",
  opts = {
    load = {
      ["core.defaults"] = {}, -- Loads default behaviour
      ["core.ui.calendar"] = {},
      ["core.ui"] = {},
      ["core.ui.calendar.views.monthly"] = {},
      ["core.clipboard"] = {},
      ["core.concealer"] = {}, -- Adds pretty icons to your documents
      ["core.itero"] = {},
      ["core.promo"] = {},
      ["core.qol.todo_items"] = {},
      ["core.export.markdown"] = {},
      ["core.summary"] = {},
      ["core.integrations.image"] = {},
      ["core.manoeuvre"] = {},
      ["core.integrations.telescope"] = {},
      ["core.latex.renderer"] = {},
      ["core.highlights"] = {},
      ["core.integrations.treesitter"] = {},
      ["core.tempus"] = {},
      ["core.autocommands"] = {},
      ["core.keybinds"] = {}, -- Adds default keybindings
      ["core.completion"] = {
        config = {
          engine = "nvim-cmp",
        },
      }, -- Enables support for completion plugins
      ["core.journal"] = {}, -- Enables support for the journal module
      ["core.dirman"] = { -- Manages Neorg workspaces
        config = {
          workspaces = {
            personal notes = "~/notes/notes",
            work = "~/notes/work",
            linux = "~/notes/linux",
          },
        },
      },
    },
  },
}

Any suggestions ?

**Comment by max397574** [comment]
you need to add this repo as a dependency
